dist: xenial
language: python
python: 3.8

before_install:
  - git clone --branch=gh-pages https://github.com/xumi1993/seispy.git ./public
  - git clone --branch=master https://github.com/xumi1993/seispy.git
  - cd seispy
  - pip install .
  - cd ..

install:
  - pip install sphinx==3.5.3 sphinx_rtd_theme==0.5.2 recommonmark==0.7.1 sphinx-markdown-tables==0.0.15

script:
  - make html
  - rm -r ./public/*
  - cp -r ./build/html/* ./public
  - echo seispy.xumijian.me > ./public/CNAME

deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      branch: master
