dist: xenial
language: python
python: 3.6

before_install:
  - git clone --branch=gh-pages https://github.com/xumi1993/seispy.git ./public
  - git clone --branch=master https://github.com/xumi1993/seispy.git
  - cd seispy
  - pip install .
  - cd ..

install:
  - pip install sphinx sphinx_rtd_theme recommonmark sphinx-markdown-tables

script:
  - make html
  - rm -r ./public/*
  - cp -r ./build/html/* ./public

deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      branch: master
