dist: xenial
language: python
python: 3.6

before_install:
  - git clone --branch=gh-pages https://git.nju.edu.cn/geophy/seispy.git ./public
  - git clone --branch=master https://git.nju.edu.cn/geophy/seispy.git

install:
  - pip install sphinx sphinx_rtd_theme recommonmark

script:
  - make html
  - cp -r ./build/html/. ./public

deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      branch: master
