baseURL = "/"
languageCode = "en-us"
title = "Seispy Documentation"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Source Code"
    url = "https://github.com/xumi1993/seispy"
    weight = 2

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 3

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'Seispy is Python module for processing seismological data and calculating Receiver Functions. The advanced functions can be used to improve the Obspy.'
  homepage_image = '/images/seispy_shortcut.png'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_og_title = "Seispy Documentation"
    meta_og_type = "website"
    meta_og_url = "https://hugo-whisper.netlify.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

  [params.logo]
      mobile = "/images/seispy.png"
      standard  = "/images/seispy.png"

   [params.valine]
    enable = true
    appId = 'pDTTIwKxG0jJoQFkUaQ1Jeqo-gzGzoHsz'
    appKey = 'LjDsQoPgO74ji2IoczXTiRM5'
    notify = true  # mail notifier , https://github.com/xCss/Valine/wiki
    verify = true # Verification code
    avatar = 'mm' 
    placeholder = 'Say something...'
    visitor = false