# This is a basic workflow to help you get started with Actions

name: Deploy Seispy Docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.7'
          architecture: amd64

      # Runs a single command using the runners shell
      - name: before_install
        run: |
          git clone --branch=gh-pages https://github.com/xumi1993/seispy.git ./public
          pip install python-seispy
      
      - name: install dependence
        run: pip install sphinx==3.5.3 sphinx_rtd_theme==0.5.2 recommonmark==0.7.1 sphinx-markdown-tables==0.0.15
#         run: pip install sphinx sphinx_rtd_theme recommonmark sphinx-markdown-tables

      # Runs a set of commands using the runners shell
      - name: build docs 
#         uses: ammaraskar/sphinx-action@master
        run: |
          make html
          cp -r build/html/* public/

      - name: Commit files
        run: |
          cd ./public
          git config --local user.email "gomijianxu@gmail.com"
          git config --local user.name "xumi1993"
          git commit -m `date +"%Y.%m.%dT%H:%M%S"` -a
          
      - name: Pushes to seispy gh-pages repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'public'
          destination-github-username: 'xumi1993'
          destination-repository-name: 'seispy'
          user-email: gomijianxu@gmail.com
          target-branch: gh-pages
